services:
  - type: web
    name: TMZ-BRAND-VIP-QUIZ-VERIFICATION-BOT
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr libtesseract-dev
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python ocr_bot_fixed.py